"""PDF report generation using fpdf2.

Converts the AI analysis (which may contain light markdown) into a
branded, printable PDF document.
"""

from __future__ import annotations

import os
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos


class _PDFReport(FPDF):  # type: ignore[misc]
    """Custom FPDF subclass with a branded footer."""

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(
            0,
            10,
            f"Page {self.page_no()} | Disclaimer: Generated by AI. Consult a doctor.",
            new_x=XPos.RIGHT,
            new_y=YPos.TOP,
            align="C",
        )


def generate_pdf_report(text_content: str, output_path: str | Path) -> Path:
    """Generate a PDF report from the analysis text.

    Handles pseudo-markdown headers (``---``, ``**bold**``, bullet lists)
    and attempts to load a Unicode font for Arabic support.

    Args:
        text_content: Analysis text (may contain light markdown).
        output_path: Destination path for the PDF.

    Returns:
        The :class:`~pathlib.Path` to the generated file.
    """
    output_path = Path(output_path)
    pdf = _PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    has_unicode = _try_load_unicode_font(pdf)

    # Title
    _set_font(pdf, has_unicode, size=16, style="B")
    pdf.cell(
        0, 10, "TahalilAI Medical Analysis Report",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C",
    )
    pdf.ln(5)
    _set_font(pdf, has_unicode, size=11)

    for line in text_content.split("\n"):
        clean = line.strip()
        if not clean:
            pdf.ln(2)
            continue

        display = clean if has_unicode else _encode_latin1(clean)
        if not display:
            continue

        # Prevent "Not enough horizontal space" edge-case
        if pdf.get_x() > 180:
            pdf.ln()

        if "---" in clean:
            pdf.ln(5)
            _set_font(pdf, has_unicode, size=12, style="B")
            _safe_multi_cell(pdf, display.replace("-", "").strip())
            _set_font(pdf, has_unicode, size=11)
        elif clean.startswith("**") or clean.endswith("**") or clean.startswith("- **"):
            _safe_multi_cell(pdf, display.replace("**", ""))
        else:
            _safe_multi_cell(pdf, display)

    pdf.output(str(output_path))
    return output_path


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_WINDOWS_ARIAL = r"C:\Windows\Fonts\arial.ttf"


def _try_load_unicode_font(pdf: FPDF) -> bool:
    """Attempt to load Arial for Unicode / Arabic support."""
    if not os.path.exists(_WINDOWS_ARIAL):
        pdf.set_font("Helvetica", size=11)
        return False
    try:
        pdf.add_font("ArialUnicode", "", _WINDOWS_ARIAL)
        pdf.set_font("ArialUnicode", size=11)
        return True
    except Exception:
        pdf.set_font("Helvetica", size=11)
        return False


def _set_font(pdf: FPDF, has_unicode: bool, size: int, style: str = "") -> None:
    """Set the active font, respecting Unicode font availability."""
    if has_unicode:
        pdf.set_font("ArialUnicode", "", size)
    else:
        pdf.set_font("Helvetica", style, size)


def _encode_latin1(text: str) -> str:
    """Strip characters that cannot be encoded in Latin-1."""
    return text.encode("latin-1", "ignore").decode("latin-1")


def _safe_multi_cell(pdf: FPDF, text: str) -> None:
    """Write a multi-cell with graceful error recovery."""
    try:
        pdf.multi_cell(0, 7, text)
    except Exception:
        import contextlib

        with contextlib.suppress(Exception):
            pdf.cell(0, 7, text[:80] + "...", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
